services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:9.0.1"
    container_name: newElasticserch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    restart: on-failure

  postgres:
    image: postgres:latest
    container_name: newPostgres1
    environment:
      POSTGRES_USER: shanto
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shanto323
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure

  books:
    build:
      context: .
      dockerfile: ./books/books.dockerfile
    depends_on:
      - elasticsearch
    environment:
      - DATABASE_DSN=http://elasticsearch:9200
    restart: on-failure

  user_service:
    build:
      context: .
      dockerfile: ./user_service/app.dockerfile
    depends_on:
      - postgres
      - books
    environment:
      - DATABASE_DSN=postgres://shanto:123456@postgres:5432/shanto323?sslmode=disable
    restart: on-failure

  rest:
    build:
      context: .
      dockerfile: ./rest/rest.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - books
      - user_service
    environment:
      - BOOK_SERVICE_URL=books:8080
      - USER_SERVICE_URL=user_service:8080
    restart: on-failure

volumes:
  pgdata: {}
