syntax = "proto3";

package pb;

option go_package = "./pb";
import "google/protobuf/timestamp.proto";

message Book {
  string title = 1;
  string isbn = 2;
  string writer = 3;
  uint64 total_copies = 4;
  uint64 on_loan = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message CreateBookRequest {
  string title = 1;
  string isbn = 2;
  string writer = 3;
  uint64 total_copies = 4;
  uint64 on_loan = 5;
}
message CreateBookResponse { Book Book = 1; }

message GetBookRequest { string isbn = 1; }
message GetBookResponse { Book book = 1; }

message UpdateBookRequest { Book book = 1; }
message UpdateBookResponse { string msg = 1; }

message DeleteBookRequest { string isbn = 1; }
message DeleteBookResponse { string msg = 1; }

message GetAllBookRequest {
  int64 limit = 1;
  int64 offset = 2;
}
message GetAllBookResponse {
  int64 total_pages = 1;
  int64 total_books = 2;
  repeated Book books = 3;
}

message SearchBookRequest {
  string query = 1;
  int64 limit = 2;
  int64 offset = 3;
}
message SearchBookResponse {
  int64 total_pages = 1;
  int64 total_books = 2;
  repeated Book books = 3;
}

service BookService {
  rpc CreateBook(CreateBookRequest) returns (CreateBookResponse) {};
  rpc GetBook(GetBookRequest) returns (GetBookResponse);
  rpc UpdateBook(UpdateBookRequest) returns (UpdateBookResponse);
  rpc DeleteBook(DeleteBookRequest) returns (DeleteBookResponse);
  rpc GetAllBook(GetAllBookRequest) returns (GetAllBookResponse);
  rpc SearchBook(SearchBookRequest) returns (SearchBookResponse);
}
