syntax = "proto3";

package pb;

option go_package = "./pb";

message Book {
  string id = 1;
  string title = 2;
  string isbn = 3;
  string writer = 4;
  uint64 total_copies = 5;
  uint64 on_loan = 6;
  string crated_at = 7;
  string updated_at = 8;
}

message CreateBookRequest {
  string title = 1;
  string isbn = 2;
  string writer = 3;
  uint64 total_copies = 4;
  uint64 on_loan = 5;
}
message CreateBookResponse { Book Book = 1; }

message GetBookRequest { string isbn = 1; }
message GetBookResponse { Book book = 1; }

message UpdateBookRequest { Book book = 1; }
message UpdateBookResponse { string msg = 1; }

message DeleteBookRequest { string isbn = 1; }
message DeleteBookResponse { string msg = 1; }

message GetAllBookRequest {
  uint64 limit = 1;
  uint64 offset = 2;
}
message GetAllBookResponse { repeated Book book = 1; }

message SearchBookRequest {
  string query = 1;
  uint64 limit = 2;
  uint64 offset = 3;
}
message SearchBookResponse { repeated Book book = 1; }

service BookService {
  rpc CreateBook(CreateBookRequest) returns (CreateBookResponse) {};
  rpc GetBook(GetBookRequest) returns (GetBookResponse);
  rpc UpdateBook(UpdateBookRequest) returns (UpdateBookResponse);
  rpc DeleteBook(DeleteBookRequest) returns (DeleteBookResponse);
  rpc GetAllBook(GetAllBookRequest) returns (GetAllBookResponse);
  rpc SearchBook(SearchBookRequest) returns (SearchBookResponse);
}
